POST http://localhost:8080/api/quotes
Content-Type: application/json

< ./test-data/stockQuote2.json

###
POST http://localhost:8080/api/leverage
Content-Type: application/json

< ./test-data/leveragePrice2.json

###
GET http://localhost:8080/api/leveragePrice/APPL

###
GET http://localhost:8080/api/leveragePrice/GOOGL

###
GET http://localhost:8080/api/quotes/count/NTFLX?pastMinutes=300

###
GET http://localhost:8080/actuator/health


